version: "2.2"

services:
  mysql:
    image: mysql:8
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: slurm-bb:${TAG:-test}
    build:
      context: ../../submodules/slurm-docker-cluster
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-22-05-4-1}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-bb:${TAG:-test}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - type: bind
        source: ./jobs
        target: /jobs
      - var_log_slurm:/var/log/slurm
      - type: bind
        source: ../../../src/burst_buffer/burst_buffer.lua.example
        target: /etc/slurm/burst_buffer.lua
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  c1:
    image: slurm-bb:${TAG:-test}
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - type: bind
        source: ./jobs
        target: /jobs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: slurm-bb:${TAG:-test}
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - type: bind
        source: ./jobs
        target: /jobs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
  var_lib_mysql:
  var_log_slurm:
