name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Unit Tests
        run: docker buildx build --target testartifacts -t testartifacts --output test_artifacts .

      - name: Analyze Code Coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "test_artifacts/coverage.cobertura.xml"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 85'

      - name: Move Coverage Report
        run: ls && mv code-coverage-results.md test_artifacts/coverage.cobertura.xml

      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: test_artifacts

  publish:
    name: Publish Results
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: unit-test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "unittest.junit.xml"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          path: code-coverage-results.md
