# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Analysis
on:
  workflow_run:
    workflows: [Test]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: unit-test-results
        
      - name: Analyze Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "unittest.junit.xml"
      
      - name: Analyze Coverage Results
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "coverage.cobertura.xml"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 85'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          path: code-coverage-results.md
